### ISSUE TITLE
UserWarning: FP16 is not supported on CPU; using FP32 instead

### ISSUE THREAD

**Issue by BrunoCampos1303** [matheusbach/legen#2]
Hi, when i try to transcribe big files this error message appears to me: "UserWarning: FP16 is not supported on CPU; using FP32 instead". How can i fix this problem, please?

**Comment by matheusbach** [comment]
Hello. This issue is due to the compute_type parameter being incorrectly set to float16, which is not supported by CPUs. Because of this, Whisper warns that it is not supported and automatically selects float32. This didn't cause a problem because the fix was thankfully handled automatically. Anyway, I fixed the LeGen detection and now the alert is no longer displayed. thanks for reporting
